[package]
name = "uefi_app"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.17.0", features = ["exts", "logger"] }
log = { version = "0.4" }
uefi-services = "0.14.0"
fatfs = { version = "0.3", features = ["core_io", "alloc"], default-features = false }
